import fs from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import consola from "consola";
import pc from "picocolors";
import { isCI } from "std-env";
import * as z from "zod/v4";
import { endpoints, headers, version } from "../metadata.ts";

// Dynamically loads the schemas, way better than manually adding.
async function load(): Promise<Record<string, unknown>> {
  const rootDir = path.resolve(process.cwd(), "src/schemas");
  const schemas: Record<string, unknown> = {};

  const walk = async (dir: string) => {
    const entries = await fs.readdir(dir, { withFileTypes: true });
    for (const entry of entries) {
      const pathname = path.join(dir, entry.name);

      if (entry.isDirectory()) await walk(pathname);
      else if (entry.isFile() && entry.name.endsWith(".ts")) {
        const mod = await import(pathToFileURL(pathname).href);
        if (Object.values(mod).some((val) => val instanceof z.ZodType)) {
          const rel = path.relative(rootDir, pathname);
          schemas[rel.replace(/\\/g, "/").replace(/\.ts$/, "")] = mod;
        }
      }
    }
  };

  await walk(rootDir);
  return schemas;
}

async function build() {
  const dir = path.resolve(process.cwd(), "json");

  consola.start(`Preparing build directory: ${pc.dim(dir)}`);
  await fs.rm(dir, { recursive: true, force: true });
  await fs.mkdir(dir, { recursive: true });

  const entries = Object.entries(await load());
  consola.info(
    `Building bundled JSON Schemas for ${pc.bold(entries.length.toString())} modules...`
  );

  for (const [relative, module] of entries) {
    const parsed = path.parse(relative);
    const target = path.join(dir, parsed.dir);
    const filename = `${parsed.name.toLowerCase()}.json`;
    const pathname = path.join(target, filename);

    await fs.mkdir(target, { recursive: true });
    const schema: Record<string, z.ZodType> = {};
    if (typeof module === "object" && module !== null) {
      for (const [key, value] of Object.entries(module)) {
        if (value instanceof z.ZodType) schema[key] = value;
      }
    }

    if (Object.keys(schema).length === 0) {
      consola.warn(`Skipping module withdir Zod exports: ${relative}`);
      continue;
    }

    const data = Object.fromEntries(
      Object.entries(schema).map(([key, value]) => {
        const json = value.toJSONSchema({
          unrepresentable: ({ zodSchema }) =>
            zodSchema._zod.def.type === "date"
              ? { type: "string", format: "date-time" }
              : "throw",
        });
        return [key, json];
      })
    );

    await fs.writeFile(pathname, JSON.stringify(data, null, 2), "utf-8");
    if (!isCI) {
      consola.success(`Wrote ${pc.cyan(path.join(parsed.dir, filename))}`);
    }
  }

  const writeArtifact = async (filename: string, content: string) => {
    await fs.writeFile(path.join(dir, filename), content, "utf-8");
    if (!isCI) consola.success(`Wrote ${pc.magenta(filename)}`);
  };

  const readme = `# Lodestone Selectors

Hello and welcome! This folder has been automatically generated by our schema build pipeline. These raw JSON files mirror the source layout and are compiled directly from our source [Zod](https://zod.dev/) definitions, compliant with JSON Schema \`draft-2020-12\`.

> **Note:** Do not edit these JSON files directly. Any changes should be made to the Zod source schemas in \`/src\`, which will automatically regenerate these artifacts during build.`;

  const metadata = {
    version,
    headers,
    endpoints: Object.fromEntries(
      Object.entries(endpoints).map(([key, value]) => [`${key}.json`, value])
    ),
  };

  await Promise.all([
    writeArtifact("README.md", readme),
    writeArtifact("metadata.json", JSON.stringify(metadata, null, 2)),
  ]);

  consola.ready(
    `${pc.green("Build complete!")} Artifacts generated in ${pc.dim(dir)}`
  );
}

build().catch((err) => {
  consola.error("Build process failed:", err);
  process.exit(1);
});
